package com.example.excel;

import com.example.excel.service.ExcelGeneratorService;

import java.util.*;

public class App {

    public static void main(String[] args) throws Exception {

        Map<String, List<String>> data = new LinkedHashMap<>();
        data.put("Email", List.of());
        data.put("First Name", List.of());
        data.put("Last Name", List.of());
        data.put("Jurisdiction", List.of(
                "United States",
                "Alaska",
                "Alabama",
                "Arkansas",
                "Arizona",
                "California",
                "Colarado",
                "Connecticut",
                "District Of Columbia",
                "Delaware",
                "Florida",
                "Georgia",
                "Hawaii",
                "Iowa",
                "Idaho",
                "Illinois",
                "Indiana",
                "Kansas",
                "Kentucky",
                "Louisiana",
                "Massachusetts",
                "Maryland",
                "Maine",
                "Michigan",
                "Minnesota",
                "Missouri",
                "Mississippi",
                "Montana",
                "North Carolina",
                "North Dakota",
                "Nebraska",
                "New Hampshire",
                "New Jersey",
                "New Mexico",
                "Nevada",
                "New York",
                "Ohio",
                "Oklahoma",
                "Oregon",
                "Pennsylvania",
                "Rhode Island",
                "South Carolina",
                "South Dakota",
                "Tennessee",
                "Texas",
                "Utah",
                "Virginia",
                "Vermont",
                "Washington",
                "Wisconsin",
                "West Virginia",
                "Wyoming",
                "Cananda",
                "Alberta",
                "British Columbia",
                "Manitoba",
                "New Brunswick",
                "Newfoundland and Labrador",
                "Nova Scotia",
                "Northwest Territories",
                "Nunavut",
                "Ontario",
                "Prince Edward Island",
                "Quebec",
                "Saskatchewan",
                "Yukon"));
        data.put("Exemption Category", List.of(
                "Agricultural",
                "Approved Economic Development Location (Enterprise Zone Exemption)",
                "Automobile Repair Services",
                "Blind Individual",
                "Charitable Nonprofit",
                "Childcare Facility",
                "Church",
                "Civic",
                "Commercial Enterprise or Business User of Computers and Software",
                "Commercial Farm - Purchasing Equipment and Machinery",
                "Commercial Farm - Purchasing Supplies and Materials",
                "Commercial Fishing",
                "Commercial Forestry",
                "Contruction Contractor - Registered as a Seller for Sales Tax Purposes",
                "Direct Pay Permit Holder",
                "Disabled Veteran - Purchase in Okahoma",
                "Federal Agency",
                "Film",
                "Food Wholesale",
                "Foreign Diplomat",
                "Gas, electric or Sanitization service provider",
                "General Exporter",
                "General Repair Services",
                "General Retail",
                "General Service Provider Selling Goods at Retail",
                "General Wholesale",
                "Government Contractor - Federal Contracts",
                "Government Contractor - Local Contracts",
                "Government Contractor - State Contracts",
                "Grocery and Convenience Store Retail",
                "Horse Racing and Horse Breeding Facilities",
                "Hotel and Hospitality Services",
                "Interstate Freight Carrier",
                "Interstate Passenger Carrier",
                "Liqour and Alcoholic Beverage Retail",
                "Local Government",
                "Manufacturer - Purchasing Equipment used in Manufacturing",
                "Manufacturer - Purchasing Materials for Resale in Manufactured Products",
                "Meat Products Retail",
                "Membership Organization",
                "Native American Enrolled Individual on Reservation",
                "Oklahoma Disabled Veteran",
                "Other Construction Contractor",
                "Other Farming Operations",
                "Private College",
                "Private School",
                "Public College",
                "Public School",
                "Resident of a Neighboring State without Sales Tax",
                "Social Service or Counseling Organization",
                "State Agency",
                "Tribal Government"));
        data.put("Expiry Date", List.of());

        ExcelGeneratorService.generate("dependent_dropdown.xlsx", data);

        System.out.println("✅ Excel file generated successfully");
    }
}
